#!/usr/bin/env python
# -*- coding: utf-8 -*-

#  Copyright 2026 Abdelkrime Aries <kariminfo0@gmail.com>
#
#  ---- AUTHORS ----
# 2026	Abdelkrime Aries <kariminfo0@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

import re
from typing import List, Dict, Optional

from . import Work, AuthorCandidate
from .tools import fetch_page, web_search

from bs4 import BeautifulSoup

SCIENCEDIRECT_AUTHOR = "sciencedirect.com/author"



def get_ids(name: str, max_results: int = 5) -> List[AuthorCandidate]:
    """
    Find candidate ScienceDirect author profiles by name, via web search.

    ScienceDirect author profiles are actually Scopus Author profiles
    embedded into ScienceDirect (Elsevier's "Scopus author pages on
    ScienceDirect" feature) — the numeric id in the profile URL
    (e.g. "55666793600") is the author's Scopus Author ID, not something
    unique to ScienceDirect. There's no dedicated author-search API, so
    this finds candidates from profile page URLs
    (sciencedirect.com/author/{scopus_id}/{slug}) surfaced in search
    results, same pattern as the IEEE module.

    affiliation/email_domain/interests are not derivable from search
    snippets and are always None / [] here.
    """
    query = f'"{name}" site:{SCIENCEDIRECT_AUTHOR}'
    raw_results = web_search(query)

    candidates: List[AuthorCandidate] = []
    seen_ids = set()

    for res in raw_results:
        url = res.get("url", "")
        match = re.search(r"sciencedirect\.com/author/(\d+)", url)
        if not match:
            continue
        author_id = match.group(1)
        if author_id in seen_ids:
            continue
        seen_ids.add(author_id)

        candidates.append(
            AuthorCandidate(id=author_id, name=res.get("title", name))
        )
        if len(candidates) >= max_results:
            break

    return candidates


def get_interests(author_id) -> List[str]:
    """
    Parse an author's topics/keywords from their ScienceDirect (Scopus)
    author profile page.

    ScienceDirect Topics on an author page are automatically generated by
    an algorithm that extracts keywords directly from the author's
    published documents indexed on ScienceDirect — same mechanism as
    IEEE Xplore's "Publication Topics", just a different source page.

    Args:
        author_id: numeric Scopus Author ID as it appears in the profile
            URL, e.g. "55666793600" for Yann LeCun

    Returns:
        List of topic strings. Empty list if the keywords container isn't
        found (e.g. page blocked, layout changed, or author has no topics
        listed).
    """
    url = f"https://www.{SCIENCEDIRECT_AUTHOR}/{author_id}"

    resp = fetch_page(url)
    if not resp:
        return []

    soup = BeautifulSoup(resp.text, "html.parser")

    container = soup.find("div", class_="keywords-container")
    if container is None:
        return []

    interests = []
    for a in container.find_all("a"):
        text = a.get_text(strip=True)
        if text:
            interests.append(text.rstrip(","))

    return interests
